freight:
  vehicle:
    km-per-liter-consumption: 10
    fuel-price: 6.30
    maintenance-cost-per-km: 0.15
    tire-cost-per-km: 0.04
    depreciation-cost-per-km: 0.53
    insurance-cost-per-km: 0.14
  delivery-person:
    base-salary: 1600.00
    charges-percentage: 39.37
    monthly-hours-worked: 192
    administrative-costs-percentage: 15
  margin:
    margin-percentage: 20
    fixed-fee: 3.00
